"""rename content to comment in reviews

Revision ID: 87fa3a6fa140
Revises: 4ff9fffb1b8f
Create Date: 2025-09-16 16:13:20.683464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fa3a6fa140'
down_revision: Union[str, Sequence[str], None] = '4ff9fffb1b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
